export const SET_PARTNERS_LOADING_STATE = 'SET_PARTNERS_LOADING_STATE';
export const FETCH_PARTNERS = 'FETCH_PARTNERS';
export const FETCH_PARTNERS_SUCCESS = 'FETCH_PARTNERS_SUCCESS';
export const SWITCH_LIST_VIEW = 'SWITCH_LIST_VIEW';
